before_script:
  - rm -rf dist/*
  - npm install -q

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

dist:
  image: axios/sigplot-buildenv:latest
  script:
    - grunt jsbeautifier:cleanup
    - grunt dist
  artifacts:
    paths:
      - dist/sigplot*.zip
